name: Release to FoundryVTT

on:
  release:
    types: [published]

permissions:
  contents: write  # Grants permission to upload assets to the release

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Extract Version Without "v" Prefix
        run: |
          VERSION="${GITHUB_REF#refs/tags/v}"
          echo "VERSION=$VERSION" >> $GITHUB_ENV

      - name: Update module.json with the Release Version
        run: |
          jq --arg version "$VERSION" '.version = $version' dist/module.json > temp.json && mv temp.json dist/module.json

      - name: Prepare Release Artifacts
        run: |
          mv dist crlngn-ui
          zip -r module.zip crlngn-ui
          mv crlngn-ui dist  # Rename back to prevent issues later

      - name: Upload Release Assets
        uses: softprops/action-gh-release@v1
        with:
          files: |
            module.zip
            dist/module.json
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Publish to FoundryVTT and Capture Response
        env:
          FOUNDRY_PACKAGE_API_KEY: ${{ secrets.FOUNDRY_PACKAGE_API_KEY }}
        run: |
          echo "Sending release data to FoundryVTT API..."
          API_RESPONSE=$(curl -s -X POST "https://api.foundryvtt.com/_api/packages/release_version/" \
            -H "Content-Type: application/json" \
            -H "Authorization: $FOUNDRY_PACKAGE_API_KEY" \
            -d '{
              "id": "crlngn-ui",
              "release": {
                "version": "'"$VERSION"'",
                "manifest": "https://github.com/${{ github.repository }}/releases/download/${{ github.event.release.tag_name }}/module.json",
                "notes": "https://github.com/${{ github.repository }}/releases/tag/${{ github.event.release.tag_name }}",
                "compatibility": {
                  "minimum": "12.328",
                  "verified": "12.331"
                }
              }
            }')
          echo "API Response: $API_RESPONSE"
